import { VehicleValidation } from '@/utils'

describe('VehicleValidation', () => {
	it('should validate license plate correctly', () => {
		expect(VehicleValidation.licensePlate('XYZ12345')).toBe(true)
		expect(VehicleValidation.licensePlate('XYZ1234A')).toBe(true)
		expect(VehicleValidation.licensePlate('XYZ123AC')).toBe(true)
		expect(VehicleValidation.licensePlate('XY12345')).toBe(true)
		expect(VehicleValidation.licensePlate('XY1234A')).toBe(true)
		expect(VehicleValidation.licensePlate('XY123AB')).toBe(true)
		expect(VehicleValidation.licensePlate('XY1A234')).toBe(true)
		expect(VehicleValidation.licensePlate('XY1AB23')).toBe(true)
		expect(VehicleValidation.licensePlate('XYZA123')).toBe(true)
		expect(VehicleValidation.licensePlate('XYZ1A23')).toBe(true)
		expect(VehicleValidation.licensePlate('XYZ12A3')).toBe(true)
		expect(VehicleValidation.licensePlate('XYZ1AC2')).toBe(true)
		expect(VehicleValidation.licensePlate('XYZAC12')).toBe(true)
		expect(VehicleValidation.licensePlate('XYZA12C')).toBe(true)
		expect(VehicleValidation.licensePlate('XYZA1CE')).toBe(true)
		expect(VehicleValidation.licensePlate('XYZ123A')).toBe(true)
		expect(VehicleValidation.licensePlate('XYZ12AC')).toBe(true)
		expect(VehicleValidation.licensePlate('XY1234')).toBe(true)
		expect(VehicleValidation.licensePlate('XY123A')).toBe(true)
		expect(VehicleValidation.licensePlate('XY12A3')).toBe(true)
		expect(VehicleValidation.licensePlate('XY1A23')).toBe(true)
		expect(VehicleValidation.licensePlate('XYA123')).toBe(true)
		expect(VehicleValidation.licensePlate('XY12AC')).toBe(true)
		expect(VehicleValidation.licensePlate('XY1AC2')).toBe(true)
		expect(VehicleValidation.licensePlate('XYAC12')).toBe(true)
		expect(VehicleValidation.licensePlate('X123')).toBe(true)
		expect(VehicleValidation.licensePlate('X12A')).toBe(true)
		expect(VehicleValidation.licensePlate('X1A2')).toBe(true)
		expect(VehicleValidation.licensePlate('XA12')).toBe(true)
		expect(VehicleValidation.licensePlate('X1AC')).toBe(true)
		expect(VehicleValidation.licensePlate('XAC1')).toBe(true)
		expect(VehicleValidation.licensePlate('XA1C')).toBe(true)
		expect(VehicleValidation.licensePlate('WI99021')).toBe(true)
		expect(VehicleValidation.licensePlate('C009')).toBe(true)
		expect(VehicleValidation.licensePlate('WK4709')).toBe(true)
		expect(VehicleValidation.licensePlate('F20156')).toBe(true)
		expect(VehicleValidation.licensePlate('D33313')).toBe(true)
		expect(VehicleValidation.licensePlate('W2AW')).toBe(true)
		expect(VehicleValidation.licensePlate('S0715B')).toBe(true)
		expect(VehicleValidation.licensePlate('P2700P05')).toBe(true)
		expect(VehicleValidation.licensePlate('GD978UY')).toBe(true)
		expect(VehicleValidation.licensePlate('E68V')).toBe(true)
		expect(VehicleValidation.licensePlate('P0KAZIK')).toBe(true)
		expect(VehicleValidation.licensePlate('SZ08A')).toBe(true)
		expect(VehicleValidation.licensePlate('ST7039T')).toBe(true)
		expect(VehicleValidation.licensePlate('st7039T')).toBe(false)
		expect(VehicleValidation.licensePlate(' st7039T  ')).toBe(false)
		expect(VehicleValidation.licensePlate('ABC123#')).toBe(false)
		expect(VehicleValidation.licensePlate('AB')).toBe(false)
		expect(VehicleValidation.licensePlate('')).toBe(false)
		expect(VehicleValidation.licensePlate('#')).toBe(false)
		expect(VehicleValidation.licensePlate('kk3476p')).toBe(false)
		expect(VehicleValidation.licensePlate(' k k 3 4 7 6 p ')).toBe(false)
		expect(VehicleValidation.licensePlate(' kk3476p ')).toBe(false)
		expect(VehicleValidation.licensePlate('111')).toBe(false)
		expect(VehicleValidation.licensePlate('1111')).toBe(false)
		expect(VehicleValidation.licensePlate('AAAAAAAA')).toBe(false)
	})

	it('should validate VIN correctly', () => {
		expect(VehicleValidation.vin('VF1RFB00968678630')).toBe(true)
		expect(VehicleValidation.vin('JTMDW3FV30D529584')).toBe(true)
		expect(VehicleValidation.vin('SUP115CC602393939')).toBe(true)
		expect(VehicleValidation.vin('1HGCM82633A12345')).toBe(false)
		expect(VehicleValidation.vin('')).toBe(false)
	})

	it('should validate date correctly', () => {
		expect(VehicleValidation.date('12.06.2018')).toBe(true)
		expect(VehicleValidation.date('28.02.2023')).toBe(true)
		expect(VehicleValidation.date('12.14.2018')).toBe(false)
		expect(VehicleValidation.date('12.06.')).toBe(false)
		expect(VehicleValidation.date('2023-08-01T00:00:00Z')).toBe(false)
		expect(VehicleValidation.date('2025-09-01T14:30:00Z')).toBe(false)
		expect(VehicleValidation.date('2022-07-04')).toBe(false)
		expect(VehicleValidation.date('-2022-07-04')).toBe(false)
		expect(VehicleValidation.date('2022-17-04')).toBe(false)
		expect(VehicleValidation.date('20.12.2500')).toBe(false)
		expect(VehicleValidation.date('')).toBe(false)
	})
})
